/*
 * hardware_defines.h
 *
 * Created: 22.07.2015 13:26:37
 *  Author: Ne0n
 */ 


#ifndef HARDWARE_DEFINES_H_
#define HARDWARE_DEFINES_H_

#include <avr/io.h>

//DISPLAY LEDS

#define DDR_LED_DISPLAY_LOSS DDRB
#define PORT_LED_DISPLAY_LOSS PORTB
#define STATE_LED_DISPLAY_LOSS PINB
#define	PIN_LED_DISPLAY_LOSS 0

#define DDR_LED_DISPLAY_8 DDRB
#define PORT_LED_DISPLAY_8 PORTB
#define STATE_LED_DISPLAY_8 PINB
#define	PIN_LED_DISPLAY_8 1

#define DDR_LED_DISPLAY_16 DDRB
#define PORT_LED_DISPLAY_16 PORTB
#define STATE_LED_DISPLAY_16 PINB
#define	PIN_LED_DISPLAY_16 2

#define DDR_LED_DISPLAY_32 DDRB
#define PORT_LED_DISPLAY_32 PORTB
#define STATE_LED_DISPLAY_32 PINB
#define	PIN_LED_DISPLAY_32 3

#define DDR_LED_DISPLAY_64 DDRB
#define PORT_LED_DISPLAY_64 PORTB
#define STATE_LED_DISPLAY_64 PINB
#define	PIN_LED_DISPLAY_64 4

#define DDR_LED_DISPLAY_WIN DDRB
#define PORT_LED_DISPLAY_WIN PORTB
#define STATE_LED_DISPLAY_WIN PINB
#define	PIN_LED_DISPLAY_WIN 5

//FIELD LEDS

#define DDR_LED_FIELD_0 DDRD
#define PORT_LED_FIELD_0 PORTD
#define STATE_LED_FIELD_0 PIND
#define PIN_LED_FIELD_0 0

#define DDR_LED_FIELD_1 DDRD
#define PORT_LED_FIELD_1 PORTD
#define STATE_LED_FIELD_1 PIND
#define PIN_LED_FIELD_1 1

#define DDR_LED_FIELD_2 DDRD
#define PORT_LED_FIELD_2 PORTD
#define STATE_LED_FIELD_2 PIND
#define PIN_LED_FIELD_2 2

#define DDR_LED_FIELD_3 DDRD
#define PORT_LED_FIELD_3 PORTD
#define STATE_LED_FIELD_3 PIND
#define PIN_LED_FIELD_3 3

#define DDR_LED_FIELD_4 DDRD
#define PORT_LED_FIELD_4 PORTD
#define STATE_LED_FIELD_4 PIND
#define PIN_LED_FIELD_4 4

#define DDR_LED_FIELD_5 DDRD
#define PORT_LED_FIELD_5 PORTD
#define STATE_LED_FIELD_5 PIND
#define PIN_LED_FIELD_5 5

#define DDR_LED_FIELD_6 DDRD
#define PORT_LED_FIELD_6 PORTD
#define STATE_LED_FIELD_6 PIND
#define PIN_LED_FIELD_6 6

#define DDR_LED_FIELD_7 DDRD
#define PORT_LED_FIELD_7 PORTD
#define STATE_LED_FIELD_7 PIND
#define PIN_LED_FIELD_7 7

//MODE LED

#define DDR_LED_MODE_GREEN DDRB
#define PORT_LED_MODE_GREEN PORTB
#define STATE_LED_MODE_GREEN PINB
#define PIN_LED_MODE_GREEN 6

#define DDR_LED_MODE_RED DDRB
#define PORT_LED_MODE_RED PORTB
#define STATE_LED_MODE_RED PINB
#define PIN_LED_MODE_RED 7

//BUTTONS

#define DDR_BUTTON_RED DDRC
#define PORT_BUTTON_RED PORTC
#define STATE_BUTTON_RED PINC
#define PIN_BUTTON_RED 0

#define DDR_BUTTON_BLUE DDRC
#define PORT_BUTTON_BLUE PORTC
#define STATE_BUTTON_BLUE PINC
#define PIN_BUTTON_BLUE 1

#define DDR_BUTTON_GREEN DDRC
#define PORT_BUTTON_GREEN PORTC
#define STATE_BUTTON_GREEN PINC
#define PIN_BUTTON_GREEN 2

#define DDR_BUTTON_YELLOW DDRC
#define PORT_BUTTON_YELLOW PORTC
#define STATE_BUTTON_YELLOW PINC
#define PIN_BUTTON_YELLOW 3

#define DDR_BUTTON_MODE DDRC
#define PORT_BUTTON_MODE PORTC
#define STATE_BUTTON_MODE PINC
#define PIN_BUTTON_MODE 4

#define DDR_BUTTON_START DDRC
#define PORT_BUTTON_START PORTC
#define STATE_BUTTON_START PINC
#define PIN_BUTTON_START 5



#endif /* HARDWARE_DEFINES_H_ */